### ISSUE TITLE
Find out which sensors are on the EPS and how they are connected to the COBC

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_SW#211]
### Description

This should be as easy as checking out the schematics of the EPS and/or asking David F.

**Comment by elenajochum** [comment]
An SPI bus with 3 chip select (CS) lines goes from the COBC via the CSBI (cubesat bus interface) to the EPS. Via this, three ADCs can be read out:

<img width="376" alt="ADCs" src="https://github.com/SpaceTeam/STS1_COBC_SW/assets/133393136/071d4811-89dd-4346-89b0-73f7eb9e39b0">

There also is a python script that shows how to read out data from the housekeeping data interface (according to David F. the battery voltage). When executed from the EDU, it continuously fetches data from the ADC and writes it to a file.

**Comment by PatrickKa** [comment]
EPS 2.0 uses [MAX11632EEG+T](https://data.space.tuwien.ac.at/index.php/f/1229331) as ADCs.
