### ISSUE TITLE
Use Serial library in command parser

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#25]
### Description

CommandParserThread.cpp still uses `CopyFrom()` to handle commands. Use the newly available Serial library instead.

**Files**
Sts1CobcSw/CommandParserThread.cpp

**Comment by PatrickKa** [comment]
Blocked by #31

**Comment by PatrickKa** [comment]
#31 is done, so this is no longer blocked

**Comment by PatrickKa** [comment]
This was already fixed in #18.

**Comment by PatrickKa** [comment]
This was already fixed in #18.
