### ISSUE TITLE
Use type_safe for EduProgramQueue

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#27]
**Description:**
Use type_safe types for fields of structures `EduQueueEntry` and `StatusHistoryEntry`.

**Files**
Sts1CobcSw/EduProgramQueue.hpp

**Comment by jeromehue** [comment]
Fixed by 20850e634f3a6be07d17987218db54b46f6dfc91 and cf4a61cb804378a3b3f38d124fc6b490e508118f

**Comment by PatrickKa** [comment]
Merged by #18
