### ISSUE TITLE
Check if including Rodos header in `Time.hpp` is necessary

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#35]
**Description**
If only `timemodel.h` is included, this would allow Utility to be combined with Catch2 without defining two mains.

**File**
Sts1CobcSw/Utility/Time.hpp

**Comment by jeromehue** [comment]
It is not but we need PRINTF function, so at least we need to include rodos-debug.h in addition to timemodel.h

**Comment by jeromehue** [comment]
Unfortunately, even if it is possible not to include `rodos.h`, as long as we link the rodos library and Catch2, we will have an error at linking time.

**Comment by PatrickKa** [comment]
So in conclusion, including the whole Rodos header is not necessary, but that does not help with the actual problem which is the linker error when using Catch2 and the Utility library.
