### ISSUE TITLE
Rework low-level code for serial interfaces

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#38]
### Description

I am very unhappy with these "type-safe" wrappers for the communication functions. They are only more cumbersome to use without adding too much value. Such low-level functions should focus more on being generic and simple. Basically, the wrong level of abstraction was chosen. `void *` is the vocabulary type for "just a bunch of bytes" therefore such low-level interfaces should expose functions taking that + a length. Maybe we can add a super thin abstraction that bundles the `void *` pointer and size, but that's it. For convenience, however, it would be nice to add an overload just taking a `T` which internally does `&T` and `sizeof(T)`. But hey, maybe I'll change my mind again soon 🤷‍♂️.

**Comment by PatrickKa** [comment]
After thinking about it some more, I would like to have some type safety and not just `void *` plus length. It's just that the current implementation is not very good (=user-friendly). In the ideal case, there is only a single function that tells the user that it reads or writes a single "scalar" value or a contiguous range of values. Splitting this into two separate overloads is the next best thing. Unfortunately, getting this right with const correctness and everything is nontrivial in C++ (see https://brevzin.github.io/c++/2021/09/10/deep-const/), so I might end up with three or four functions that read from a single value or range.

More experimenting and prototyping is required from my side before I can really rework `Communication.hpp`.

**Comment by PatrickKa** [comment]
The solution I currently favor is to provide only a single function template that takes a `std::span`. Additionally, I provide convenient functions to convert single objects or arrays to spans (with the right deep constness). Those conversion functions are called `Span()` and take by constant reference or by pointer to decide if a read-only span or a span with mutable elements should be created. `Span()` should be the first choice whenever a `std::span` needs to be created.
