### ISSUE TITLE
Move global edu variable to Edu.hpp/.cpp

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#48]
### Description

Edu.hpp is the file that is surely included if someone wants to use the EDU so the global variable should be declared there. Of course the definition should then be in Edu.cpp.

**Comment by PatrickKa** [comment]
I think it should be declared in Edu.hpp because that is the file that is surely included, if someone wants to use the EDU. Of course the definition then has to be in Edu.cpp.
