### ISSUE TITLE
ringbuffer.h can be included without specifying rodos/support-libs/

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#49]
**Description**
Change install rules of rodos such that ringbuffer.h must be included as rodos/support-libs/ringbuffer.h or something.

**File**
Sts1CobcSw/EduProgramQueue.hpp

**Comment by jeromehue** [comment]
Actually, it can already be rewritten as :
`#include <rodos/support/support-libs/ringbuffer.h>`
Since rodos is installed under `/usr/local/include` or some default install location on the machine.

**Comment by PatrickKa** [comment]
This is actually an issue for the https://github.com/SpaceTeam/rodos

**Comment by PatrickKa** [comment]
I added the issue in our rodos repo. What's left to do here is to only use `#include <rodos/support/support-libs/ringbuffer.h>` to include ringbuffer.h.
