### ISSUE TITLE
Use utility function for printing time in BuildQueueCommand test

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#58]
**Description**
Now that there is a function for printing time in Utility, use it instead of redefining it in the test file.

**File**
Tests/GoldenTests/BuildQueueCommand.test.cpp

**Comment by PatrickKa** [comment]
Title and description must be updated according to the new issue templates.

**Comment by PatrickKa** [comment]
BuildQueueCommand.test.cpp no longer exists
