### ISSUE TITLE
Remove tests for single EDU commands

### ISSUE THREAD

**Issue by PatrickKa** [SpaceTeam/STS1_COBC_SW#75]
`EduCommands.test.cpp` is superior to the tests with single EDU commands because it is much more convenient for the tester. Therefore, the single command tests are not used anymore and should be removed. Since the `EduCommandTests` directory would then only contain a single test, it can be removed as well and the test be moved up one level.

**Comment by shivamxsurya** [comment]
Feel free to assign this to me

**Comment by shivamxsurya** [comment]
pull request made for the removal of the tests for single EDU commands #78
